"""Seed Kawari Wholesalers (B00000047) portal account, risks, and policy schedule."""
from __future__ import annotations

import json
import uuid
from pathlib import Path

ACCOUNT_ID = "b1111111-1111-4111-8111-111111111147"
PARENT_ACCOUNT_ID = "3a842763-e5f2-43f7-87c2-2a5429738fb3"
POLICY_ID = "c2222222-2222-4222-8222-222222222247"
ZOHO_ACCOUNT_ID = "7351644000003979001"
# Filled after Zoho policy create; override via env or edit below
ZOHO_POLICY_ID = "PLACEHOLDER_ZOHO_POLICY_ID"

NS = uuid.UUID("b0000004-7aaa-4bbb-8ccc-dddddddddddd")

POLICY = {
    "policyId": 15785,
    "policyNumber": "B00000047",
    "inceptionDate": "2025-07-01",
    "renewalDate": "2026-09-01",
    "status": "Active",
    "frequency": "Monthly",
    "product": "Bryte Commercial (Kolonie)",
    "insurer": "Bryte Insurance Company South Africa",
    "totalPremium": 12423.908815,
    "totalSasriaPremium": 249.678663,
    "totalFeePremium": 95.65,
    "risks": [
        {
            "trackingId": "773463fc-c35d-419b-a96d-320f3cb582e9",
            "riskId": 59137,
            "section": "Fire",
            "sectionType": "Generic",
            "description": "Crescent Corporate Park, Unit A1, Block A, Technohub 59 Roan, Midrand, Gauteng, 1682",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 4133365.5,
            "premium": 742.208609,
            "premiumIncl": 853.53990035,
            "ratingFactors": [
                {"group": "", "questionAnswer": {"rate": "0.236100%", "description": "Crescent Corporate Park, Unit A1, Block A, Technohub 59 Roan, Midrand, Gauteng, 1682"}},
                {"group": "Building", "questionAnswer": {"building Type": ""}},
                {"group": "Insured perils", "questionAnswer": {"earthquake": "Yes", "special perils": "Yes"}},
            ],
            "kind": "location",
            "category": "Building",
        },
        {
            "trackingId": "1d3dd30d-fb81-434a-9340-fbd6892bfbe6",
            "riskId": 59138,
            "section": "Office Contents",
            "sectionType": "Generic",
            "description": "Crescent Corporate Park, Unit A1, Block A, Technohub 59 Roan, Midrand, Gauteng, 1682",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 1306028.9,
            "premium": 317.989645,
            "premiumIncl": 365.68809175,
            "ratingFactors": [
                {"group": "", "questionAnswer": {"security": "Unspecified", "building Type": ""}},
                {"group": "Subsection A - Contents", "questionAnswer": {"rate": "0.336000%", "burglar Alarm Warranty applicable": "0"}},
            ],
            "kind": "location",
            "category": "Contents",
        },
        {
            "trackingId": "7a7997bc-24bc-4731-9757-ddd577a06b56",
            "riskId": 59139,
            "section": "Accidental Damage",
            "sectionType": "Generic",
            "description": "Crescent Corporate Park, Unit A1, Block A, Technohub 59 Roan, Midrand, Gauteng, 1682",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 2185932.0,
            "premium": 282.936609,
            "premiumIncl": 325.37710035,
            "ratingFactors": [
                {"group": "", "questionAnswer": {"rate": "0.110000%", "description": "Crescent Corporate Park…", "basis of Cover": "Full Value"}},
            ],
            "kind": "cover",
            "category": "Miscellaneous",
        },
        {
            "trackingId": "0f113211-8052-4382-8ed2-8aad19c9f56c",
            "riskId": 59140,
            "section": "Theft",
            "sectionType": "Generic",
            "description": "Crescent Corporate Park, Unit A1, Block A, Technohub 59 Roan, Midrand, Gauteng, 1682",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 100000.0,
            "premium": 376.231884,
            "premiumIncl": 432.6666666,
            "ratingFactors": [
                {"group": "", "questionAnswer": {"rate": "5.192000%", "basis": "First Loss", "burglar Alarm Warranty": "1"}},
            ],
            "kind": "cover",
            "category": "Miscellaneous",
        },
        {
            "trackingId": "d668f28f-091d-4113-8847-59dea180182a",
            "riskId": 59141,
            "section": "Electronic Equipment",
            "description": "16x PC's or electronic equipment in administration offices @ R8,000 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 128000.0,
            "premium": 327.513043,
            "premiumIncl": 376.63999945,
            "serial": "",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "3.210000%", "description": "16x PC's or electronic equipment in administration offices @ R8,000 each"}}],
        },
        {
            "trackingId": "705b8f45-771c-43ef-9062-1fe2f15f5f1d",
            "riskId": 59142,
            "section": "Electronic Equipment",
            "description": "Complete server room with accessories",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 200000.0,
            "premium": 511.73913,
            "premiumIncl": 588.4999995,
            "serial": "",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "3.210000%", "description": "Complete server room with accessories"}}],
        },
        {
            "trackingId": "bf3d6a50-1c08-4eaa-b6dc-7fe73e5f7ebe",
            "riskId": 59143,
            "section": "Electronic Equipment",
            "description": "16x Telephone Handsets @ R2,000 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 32000.0,
            "premium": 81.878261,
            "premiumIncl": 94.16000015,
            "serial": "",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "3.210000%"}}],
        },
        {
            "trackingId": "c1dfca4a-ccba-4798-b6ed-34e7f37ca489",
            "riskId": 59144,
            "section": "Electronic Equipment",
            "description": "11 x Printers @ R3000 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 33000.0,
            "premium": 84.436957,
            "premiumIncl": 97.10250055,
            "serial": "",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "3.531000%"}}],
        },
        {
            "trackingId": "8c03c2ff-24d8-4a90-ba47-57773b0ac350",
            "riskId": 59145,
            "section": "Electronic Equipment",
            "description": "Laptop with accessories and software",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 10550.0,
            "premium": 134.971196,
            "premiumIncl": 155.2168754,
            "serial": "LXATROX17183604E9E200",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "17.655000%", "serial number": "LXATROX17183604E9E200"}}],
        },
        {
            "trackingId": "e8373ade-2bde-4824-83cb-7a65bcf0d368",
            "riskId": 59146,
            "section": "Electronic Equipment",
            "description": '15" Retina 2.6Ghz QC 17 laptop with accessories ans software',
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 31000.0,
            "premium": 396.597826,
            "premiumIncl": 456.0874999,
            "serial": "SC02J63HWDKQ2",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "17.655000%", "serial number": "SC02J63HWDKQ2"}}],
        },
        {
            "trackingId": "595e0da3-81d1-4b3a-a3c9-523b65cdb951",
            "riskId": 59147,
            "section": "Electronic Equipment",
            "description": 'TM5760-2416G64MNBK / 15.6"/15-2410/6GB/640GB Acer laptop with accessories and software',
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 7560.0,
            "premium": 96.724722,
            "premiumIncl": 111.2334303,
            "serial": "LXVZW030461121E9672500",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "17.656100%", "serial number": "LXVZW030461121E9672500"}}],
        },
        {
            "trackingId": "b0ea7123-3b21-47b9-9417-6ac8eb818de4",
            "riskId": 59148,
            "section": "Electronic Equipment",
            "description": 'Travelmate TN653 15.6" i7-3520M 2laptop with accessories and software',
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 15000.0,
            "premium": 191.902174,
            "premiumIncl": 220.6875001,
            "serial": "NXV83EA002307005F92000",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "17.655000%", "make and Model": "NXV83EA002307005F92000"}}],
        },
        {
            "trackingId": "1ce45901-92d6-4378-b548-2e35a8c9f9ce",
            "riskId": 59149,
            "section": "Electronic Equipment",
            "description": 'Galaxy Tab4, 16GB, 255.8mm(10.1") WXGALCD',
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 4600.0,
            "premium": 58.853667,
            "premiumIncl": 67.68171705,
            "serial": "RF2FC005PPL",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "17.656100%", "serial number": "RF2FC005PPL"}}],
        },
        {
            "trackingId": "60da0b65-0878-4fd3-89d5-9126a8264678",
            "riskId": 59150,
            "section": "Electronic Equipment",
            "description": 'Galaxy Tab4, 16GB, 255.8mm(10.1") WXGALCD',
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 4600.0,
            "premium": 58.853667,
            "premiumIncl": 67.68171705,
            "serial": "R52G11DMWWD",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "17.656100%", "serial number": "R52G11DMWWD"}}],
        },
        {
            "trackingId": "dc170a16-1af6-4c95-b2a4-d76780468042",
            "riskId": 59151,
            "section": "Electronic Equipment",
            "description": "40A4K Hisense 40'' FHD Smart TV",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 3477.0,
            "premium": 22.172174,
            "premiumIncl": 25.4980001,
            "serial": "",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "8.800000%"}}],
        },
        {
            "trackingId": "5efff36a-d5d6-4fcb-8528-3701c0395b28",
            "riskId": 59152,
            "section": "Electronic Equipment",
            "description": "40A4K Hisense 40'' FHD Smart TV",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 3477.0,
            "premium": 22.172174,
            "premiumIncl": 25.4980001,
            "serial": "",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "8.800000%"}}],
        },
        {
            "trackingId": "08e83cde-7212-4c65-bcd4-f265677bb175",
            "riskId": 59153,
            "section": "Electronic Equipment",
            "description": "1320995 First Technology INV564094 Scanner-Canon",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 13524.0,
            "premium": 86.24,
            "premiumIncl": 99.176,
            "serial": "PNA44286",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "8.800000%", "serial number": "PNA44286"}}],
        },
        {
            "trackingId": "05b887f5-1810-43af-b22f-59c2bd558e12",
            "riskId": 59154,
            "section": "Electronic Equipment",
            "description": "1320995 Esquire Tech 922911 x1 Laptop SSD",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 8893.0,
            "premium": 56.708986,
            "premiumIncl": 65.2153339,
            "serial": "PNA45226",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "8.800000%", "serial number": "PNA45226"}}],
        },
        {
            "trackingId": "3b23887b-9550-44e9-852c-05db42a9f0cb",
            "riskId": 59155,
            "section": "Electronic Equipment",
            "description": "1320995 First Tech 587959 x3 Batteries 4x Charg",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 9385.0,
            "premium": 59.846377,
            "premiumIncl": 68.82333355,
            "serial": "PNA45397",
            "kind": "item",
            "category": "Electronic Equipment",
            "ratingFactors": [{"group": "Subsection A - Material Damage", "questionAnswer": {"rate": "8.800000%", "serial number": "PNA45397"}}],
        },
        {
            "trackingId": "df16a8b7-f18e-4f5d-af70-f1f956db4278",
            "riskId": 59156,
            "section": "Business All Risks",
            "description": "15x 2D Mobile scanners @ R12027 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 180405.0,
            "premium": 1230.937304,
            "premiumIncl": 1415.5778996,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "9.416000%"}}],
        },
        {
            "trackingId": "844510f4-b9c4-4ed9-9fac-ba326bfce862",
            "riskId": 59157,
            "section": "Business All Risks",
            "description": "30x 2D Mobile scanners with docking stations @ R10260 each (Cape Town)",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 307800.0,
            "premium": 2085.456522,
            "premiumIncl": 2398.2750003,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "9.350000%"}}],
        },
        {
            "trackingId": "bc07ed1c-8c36-49fd-993e-7432b9fcf785",
            "riskId": 59158,
            "section": "Business All Risks",
            "description": "3x Samsung Galaxy Tab S6 Lite @ R9078 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 27234.0,
            "premium": 232.278391,
            "premiumIncl": 267.12014965,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "11.770000%"}}],
        },
        {
            "trackingId": "42acf460-44ca-47af-be2d-240811abde55",
            "riskId": 59159,
            "section": "Business All Risks",
            "description": "4x Television sets",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 36500.0,
            "premium": 248.697246,
            "premiumIncl": 286.0018329,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "9.402800%"}}],
        },
        {
            "trackingId": "76c61350-8bda-45eb-ba05-a2c463d77537",
            "riskId": 59160,
            "section": "Business All Risks",
            "description": "5x 2D Mobile scanners with docking stations @ R10260 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 51300.0,
            "premium": 291.146087,
            "premiumIncl": 334.81800005,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "7.832000%"}}],
        },
        {
            "trackingId": "37605746-25c9-4703-bced-d7527379b164",
            "riskId": 59161,
            "section": "Business All Risks",
            "description": "5x IP65 Mobile rugged device 2d scanners @ R12027 each (Cape Town)",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 60135.0,
            "premium": 410.312435,
            "premiumIncl": 471.85930025,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "9.416000%"}}],
        },
        {
            "trackingId": "f95256f4-18da-4f68-9197-c07b978f2c31",
            "riskId": 59162,
            "section": "Business All Risks",
            "description": "6x Pallet jacks @ R3000 each",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 18000.0,
            "premium": 103.447826,
            "premiumIncl": 118.9649999,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "7.931000%"}}],
        },
        {
            "trackingId": "085a87e5-6d72-45b3-9e15-10626af83d6c",
            "riskId": 59163,
            "section": "Business All Risks",
            "description": "Acer PJ P1385 WB projector",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 8500.0,
            "premium": 68.024638,
            "premiumIncl": 78.2283337,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "11.044000%"}}],
        },
        {
            "trackingId": "770529f4-9393-4409-8aaf-86c58c904b53",
            "riskId": 59164,
            "section": "Business All Risks",
            "description": "Alarm System",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 50000.0,
            "premium": 170.181159,
            "premiumIncl": 195.70833285,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "4.697000%"}}],
        },
        {
            "trackingId": "ca6f83fd-72c0-46e6-90db-a23aba44cd09",
            "riskId": 59165,
            "section": "Business All Risks",
            "description": "Security camera system",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 200000.0,
            "premium": 1149.42029,
            "premiumIncl": 1321.8333335,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "7.931000%"}}],
        },
        {
            "trackingId": "dcb4808a-48a0-474b-a827-c4537b0298b0",
            "riskId": 59166,
            "section": "Business All Risks",
            "description": "Router KDC",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 13500.0,
            "premium": 86.086957,
            "premiumIncl": 99.00000055,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "8.800000%"}}],
        },
        {
            "trackingId": "6d625e85-9a81-4887-a38b-39cb9ef98944",
            "riskId": 59167,
            "section": "Business All Risks",
            "description": "Router CT",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 13500.0,
            "premium": 86.086957,
            "premiumIncl": 99.00000055,
            "serial": "",
            "kind": "item",
            "category": "Miscellaneous",
            "ratingFactors": [{"group": "", "questionAnswer": {"rate": "8.800000%"}}],
        },
        {
            "trackingId": "eafe7264-d36e-4b9b-97a9-47b44dd54102",
            "riskId": 59168,
            "section": "Public Liability",
            "description": "Crescent Corporate Park, Unit A1, Block A, Technohub 59 Roan, Midrand, Gauteng, 1682",
            "inceptionDate": "2025-07-01",
            "status": "Approved",
            "insuredAmount": 20000000.0,
            "premium": 386.017392,
            "premiumIncl": 443.9200008,
            "kind": "cover",
            "category": "Liability",
            "ratingFactors": [
                {"group": "", "questionAnswer": {"rate": "0.026400%", "basis of Cover": "Claims Made"}},
                {
                    "group": "Cover",
                    "questionAnswer": {
                        "territorial limits": "Anywhere in the world but not in connection with (i) any business carried on by the Insured at or from premises outside or  (ii) any contract for the performance of work outside  the Republic of South Africa, Namibia, Botswana, Lesotho, Swaziland, Zimbabwe"
                    },
                },
            ],
        },
    ],
}

RISK_TYPE_ZOHO = {
    "Fire": "Building",
    "Office Contents": "Office Contents",
    "Accidental Damage": "Accidental Damage",
    "Theft": "All Risk / Portable Item",
    "Electronic Equipment": "Electronic Equipment",
    "Business All Risks": "All Risk / Portable Item",
    "Public Liability": "Accidental Damage",
}


def sql_str(value: str | None) -> str:
    if value is None:
        return "null"
    return "'" + value.replace("'", "''") + "'"


def risk_uuid(risk_id: int) -> str:
    return str(uuid.uuid5(NS, f"kawari-risk-{risk_id}"))


def extensions_for(risk: dict) -> list[dict]:
    out = []
    for i, rf in enumerate(risk.get("ratingFactors") or []):
        qa = rf.get("questionAnswer") or {}
        details = {k: str(v) for k, v in qa.items() if v not in (None, "")}
        name = (rf.get("group") or "").strip() or "Cover terms"
        out.append(
            {
                "id": f"ext-{risk['riskId']}-{i}",
                "name": name,
                "sum_insured": risk["insuredAmount"],
                "premium_excl": risk["premium"] if i == 0 else None,
                "premium_incl": risk["premiumIncl"] if i == 0 else None,
                "details": details,
            }
        )
    return out


def build_covered_item(risk: dict, portal_risk_id: str) -> dict:
    return {
        "risk_item_id": portal_risk_id,
        "risk_item_name": risk["description"].strip(),
        "section": risk["section"],
        "sum_insured": risk["insuredAmount"],
        "premium_excl": risk["premium"],
        "premium_incl": risk["premiumIncl"],
        "cover_status": risk["status"],
        "description": risk["description"].strip(),
        "branch": None,
        "date_added": risk["inceptionDate"],
        "external_risk_id": str(risk["riskId"]),
        "tracking_id": risk["trackingId"],
        "extensions": extensions_for(risk),
        "attachments": [],
    }


def build_sql(zoho_policy_id: str) -> str:
    lines: list[str] = [
        "-- Kawari Wholesalers B00000047 under Medipost parent",
        "BEGIN;",
        "",
        "INSERT INTO portal_accounts (",
        "  id, name, parent_account_id, zoho_account_id, industry, registration_number, vat_number, phone, aegis_status",
        ") VALUES (",
        f"  '{ACCOUNT_ID}',",
        "  'Kawari Wholesalers (Pty) Ltd',",
        f"  '{PARENT_ACCOUNT_ID}',",
        f"  '{ZOHO_ACCOUNT_ID}',",
        "  'Commercial',",
        "  '1990/000001/01',",
        "  '000000',",
        "  '+27 (0)00 474224',",
        "  'active'",
        ")",
        "ON CONFLICT (id) DO UPDATE SET",
        "  name = EXCLUDED.name,",
        "  parent_account_id = EXCLUDED.parent_account_id,",
        "  zoho_account_id = EXCLUDED.zoho_account_id,",
        "  industry = EXCLUDED.industry,",
        "  registration_number = EXCLUDED.registration_number,",
        "  vat_number = EXCLUDED.vat_number,",
        "  phone = EXCLUDED.phone,",
        "  aegis_status = EXCLUDED.aegis_status;",
        "",
    ]

    covered: list[dict] = []
    for risk in POLICY["risks"]:
        rid = risk_uuid(risk["riskId"])
        zoho_risk_id = f"nimbis-risk-{risk['riskId']}"
        serial = (risk.get("serial") or "").strip() or None
        asset_tag = f"KW-{risk['riskId']}"
        zoho_fields = {
            "nimbis_risk_id": str(risk["riskId"]),
            "nimbis_tracking_id": risk["trackingId"],
            "nimbis_section": risk["section"],
            "nimbis_section_type": risk.get("sectionType") or "Generic",
            "policy_number": "B00000047",
            "cover_kind": risk.get("kind"),
            "sum_insured": risk["insuredAmount"],
            "premium_excl": risk["premium"],
            "premium_incl": risk["premiumIncl"],
        }
        lines += [
            "INSERT INTO portal_risk_items (",
            "  id, account_id, zoho_risk_id, name, category, insurance_section, unit_cost, repair_cost,",
            "  record_date, insurance_status, asset_tag, serial_number, description, zoho_fields",
            ")",
            "VALUES (",
            f"  '{rid}',",
            f"  '{ACCOUNT_ID}',",
            f"  {sql_str(zoho_risk_id)},",
            f"  {sql_str(risk['description'].strip())},",
            f"  {sql_str(risk['category'])},",
            f"  {sql_str(risk['section'])},",
            f"  {risk['insuredAmount']},",
            "  0,",
            f"  {sql_str(risk['inceptionDate'])},",
            "  'Insured with us',",
            f"  {sql_str(asset_tag)},",
            f"  {sql_str(serial)},",
            f"  {sql_str(risk['description'].strip())},",
            f"  {sql_str(json.dumps(zoho_fields))}::jsonb",
            ")",
            "ON CONFLICT (id) DO UPDATE SET",
            "  name = EXCLUDED.name,",
            "  category = EXCLUDED.category,",
            "  insurance_section = EXCLUDED.insurance_section,",
            "  unit_cost = EXCLUDED.unit_cost,",
            "  insurance_status = EXCLUDED.insurance_status,",
            "  serial_number = EXCLUDED.serial_number,",
            "  description = EXCLUDED.description,",
            "  zoho_fields = EXCLUDED.zoho_fields,",
            "  updated_at = now();",
            "",
        ]
        covered.append(build_covered_item(risk, rid))

    covered_json = json.dumps(covered, ensure_ascii=False)
    lines += [
        "INSERT INTO portal_policies (",
        "  id, account_id, zoho_policy_id, policy_number, insurer_policy_number, status, premium,",
        "  sasria_premium, fee_premium, inception_date, renewal_date, insurer, product_line,",
        "  frequency, covered_items",
        ") VALUES (",
        f"  '{POLICY_ID}',",
        f"  '{ACCOUNT_ID}',",
        f"  {sql_str(zoho_policy_id)},",
        "  'B00000047',",
        "  'B00000047',",
        "  'Active',",
        f"  {POLICY['totalPremium']},",
        f"  {POLICY['totalSasriaPremium']},",
        f"  {POLICY['totalFeePremium']},",
        f"  {sql_str(POLICY['inceptionDate'])},",
        f"  {sql_str(POLICY['renewalDate'])},",
        f"  {sql_str(POLICY['insurer'])},",
        f"  {sql_str(POLICY['product'])},",
        f"  {sql_str(POLICY['frequency'])},",
        f"  {sql_str(covered_json)}::jsonb",
        ")",
        "ON CONFLICT (id) DO UPDATE SET",
        "  account_id = EXCLUDED.account_id,",
        "  zoho_policy_id = EXCLUDED.zoho_policy_id,",
        "  policy_number = EXCLUDED.policy_number,",
        "  insurer_policy_number = EXCLUDED.insurer_policy_number,",
        "  status = EXCLUDED.status,",
        "  premium = EXCLUDED.premium,",
        "  sasria_premium = EXCLUDED.sasria_premium,",
        "  fee_premium = EXCLUDED.fee_premium,",
        "  inception_date = EXCLUDED.inception_date,",
        "  renewal_date = EXCLUDED.renewal_date,",
        "  insurer = EXCLUDED.insurer,",
        "  product_line = EXCLUDED.product_line,",
        "  frequency = EXCLUDED.frequency,",
        "  covered_items = EXCLUDED.covered_items;",
        "",
        # Also expose policy on parent Medipost so parent org can see Kawari schedule if needed
        "INSERT INTO portal_policies (",
        "  id, account_id, zoho_policy_id, policy_number, insurer_policy_number, status, premium,",
        "  sasria_premium, fee_premium, inception_date, renewal_date, insurer, product_line,",
        "  frequency, covered_items",
        ") VALUES (",
        f"  'd3333333-3333-4333-8333-333333333347',",
        f"  '{PARENT_ACCOUNT_ID}',",
        f"  {sql_str(zoho_policy_id)},",
        "  'B00000047',",
        "  'B00000047',",
        "  'Active',",
        f"  {POLICY['totalPremium']},",
        f"  {POLICY['totalSasriaPremium']},",
        f"  {POLICY['totalFeePremium']},",
        f"  {sql_str(POLICY['inceptionDate'])},",
        f"  {sql_str(POLICY['renewalDate'])},",
        f"  {sql_str(POLICY['insurer'])},",
        f"  {sql_str(POLICY['product'])},",
        f"  {sql_str(POLICY['frequency'])},",
        f"  {sql_str(covered_json)}::jsonb",
        ")",
        "ON CONFLICT (id) DO UPDATE SET",
        "  covered_items = EXCLUDED.covered_items,",
        "  premium = EXCLUDED.premium,",
        "  zoho_policy_id = EXCLUDED.zoho_policy_id;",
        "",
        "COMMIT;",
    ]
    return "\n".join(lines)


def zoho_client_risk_payloads() -> list[dict]:
    out = []
    for risk in POLICY["risks"]:
        out.append(
            {
                "Name": risk["description"].strip()[:120],
                "Item_Owned_By": {"id": ZOHO_ACCOUNT_ID},
                "Risk_Category": "Commercial Lines",
                "Risk_Status": "Covered With Us",
                "Risk_Type": RISK_TYPE_ZOHO.get(risk["section"], "Electronic Equipment"),
                "Total_Sum_Insured": risk["insuredAmount"],
                "Current_Premium": risk["premium"],
                "Nimbis_Risk_ID": str(risk["riskId"]),
                "Cover_Start_Date": risk["inceptionDate"],
                "Serial_Number": (risk.get("serial") or None),
            }
        )
    return out


if __name__ == "__main__":
    import sys

    zoho_policy = sys.argv[1] if len(sys.argv) > 1 else ZOHO_POLICY_ID
    root = Path(__file__).resolve().parents[1]
    sql_path = root / "data" / "seed-kawari-B00000047.sql"
    sql_path.write_text(build_sql(zoho_policy), encoding="utf-8")
    payload_path = root / "data" / "kawari-zoho-client-risks.json"
    payload_path.write_text(json.dumps(zoho_client_risk_payloads(), indent=2), encoding="utf-8")
    print(f"Wrote {sql_path}")
    print(f"Wrote {payload_path} ({len(POLICY['risks'])} risks)")
